# Generated by Django 2.1.1 on 2018-10-18 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterBasicInfo',
            fields=[
                ('cluster_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=16)),
                ('cluster_type', models.CharField(max_length=30)),
                ('cluster_version', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterHostMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_basic', to='cmdb.ClusterBasicInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentHostMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(max_length=30)),
                ('component_version', models.CharField(default='0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HostBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('ip_address', models.CharField(max_length=16)),
                ('serial', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('rack_id', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('num_cpu', models.CharField(default='', max_length=10)),
                ('num_mem', models.CharField(default='', max_length=10)),
                ('os_version', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('machine_type', models.CharField(choices=[('physical', 'physical'), ('virtual', 'virtual')], default='physical', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='componentinfo',
            name='host_info',
            field=models.ManyToManyField(through='cmdb.ComponentHostMapping', to='cmdb.HostBasicInfo'),
        ),
        migrations.AddField(
            model_name='componenthostmapping',
            name='component_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.ComponentInfo'),
        ),
        migrations.AddField(
            model_name='componenthostmapping',
            name='host_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_component', to='cmdb.HostBasicInfo'),
        ),
        migrations.AddField(
            model_name='clusterhostmapping',
            name='host_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_cluster', to='cmdb.HostBasicInfo'),
        ),
        migrations.AddField(
            model_name='clusterbasicinfo',
            name='host_info',
            field=models.ManyToManyField(through='cmdb.ClusterHostMapping', to='cmdb.HostBasicInfo'),
        ),
    ]
