# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30)),
                ('ipaddress', models.CharField(max_length=16)),
                ('serial', models.CharField(max_length=10)),
                ('rack_id', models.CharField(default=None, max_length=10)),
                ('nummem', models.CharField(max_length=10)),
            ],
        ),
    ]
