# Generated by Django 2.1.1 on 2018-10-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostbasicinfo',
            name='os_version',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
