# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='numcpu',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='nummem',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='serial',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
