# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180831_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverinfo',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
