# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180902_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='numcpu',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='nummem',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='rack_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='serial',
            field=models.CharField(default='', max_length=10),
        ),
    ]
