# Generated by Django 2.1.1 on 2018-09-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20180911_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='rack_id',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='serial',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
