# Generated by Django 2.1.1 on 2018-09-14 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_clusterbasicinfo_clusteripmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteripmapping',
            name='cluster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_basic', to='cmdb.ClusterBasicInfo'),
        ),
    ]
