# Generated by Django 2.1.1 on 2018-09-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_auto_20180914_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterbasicinfo',
            name='cluster_version',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
