# Generated by Django 2.1.1 on 2018-09-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_clusterbasicinfo_cluster_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='osversion',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
