# Generated by Django 2.1.1 on 2018-09-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0012_serverinfo_osversion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CLusterIpMapping',
            new_name='CLusterHostMapping',
        ),
        migrations.RenameModel(
            old_name='ServerInfo',
            new_name='HostBasicInfo',
        ),
    ]
