# Generated by Django 2.1.1 on 2018-09-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_auto_20180918_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterbasicinfo',
            name='host_id',
            field=models.ManyToManyField(to='cmdb.HostBasicInfo'),
        ),
    ]
