# Generated by Django 2.1.1 on 2018-09-18 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0014_clusterbasicinfo_host_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterbasicinfo',
            name='host_id',
        ),
        migrations.AddField(
            model_name='clusterbasicinfo',
            name='host_info',
            field=models.ManyToManyField(through='cmdb.ClusterHostMapping', to='cmdb.HostBasicInfo'),
        ),
        migrations.AlterField(
            model_name='clusterhostmapping',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_cluster', to='cmdb.HostBasicInfo'),
        ),
    ]
