# Generated by Django 2.1.1 on 2018-09-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0017_auto_20180918_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusterhostmapping',
            old_name='cluster_id',
            new_name='clusterinfo',
        ),
        migrations.RenameField(
            model_name='clusterhostmapping',
            old_name='ip_address',
            new_name='hostinfo',
        ),
        migrations.AlterField(
            model_name='clusterbasicinfo',
            name='host_info',
            field=models.ManyToManyField(through='cmdb.ClusterHostMapping', to='cmdb.HostBasicInfo'),
        ),
        migrations.AlterField(
            model_name='hostbasicinfo',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
