# Generated by Django 2.1.1 on 2018-09-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0018_auto_20180919_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusterhostmapping',
            old_name='clusterinfo',
            new_name='cluster_info',
        ),
        migrations.RenameField(
            model_name='clusterhostmapping',
            old_name='hostinfo',
            new_name='host_info',
        ),
        migrations.RenameField(
            model_name='hostbasicinfo',
            old_name='hostname',
            new_name='host_name',
        ),
        migrations.RenameField(
            model_name='hostbasicinfo',
            old_name='ipaddress',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='hostbasicinfo',
            old_name='numcpu',
            new_name='num_cpu',
        ),
        migrations.RenameField(
            model_name='hostbasicinfo',
            old_name='nummem',
            new_name='num_mem',
        ),
        migrations.RenameField(
            model_name='hostbasicinfo',
            old_name='osversion',
            new_name='os_version',
        ),
        migrations.AlterField(
            model_name='clusterbasicinfo',
            name='host_info',
            field=models.ManyToManyField(through='cmdb.ClusterHostMapping', to='cmdb.HostBasicInfo'),
        ),
    ]
