# Generated by Django 2.1.1 on 2018-09-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0019_auto_20180926_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostbasicinfo',
            old_name='server_type',
            new_name='machine_type',
        ),
        migrations.AlterField(
            model_name='clusterbasicinfo',
            name='host_info',
            field=models.ManyToManyField(through='cmdb.ClusterHostMapping', to='cmdb.HostBasicInfo'),
        ),
    ]
