# Generated by Django 2.1.1 on 2018-10-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0021_auto_20180928_1743'),
        ('cmdb', '0021_auto_20180928_1539'),
    ]

    operations = [
    ]
