# Generated by Django 2.1.1 on 2018-10-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0022_merge_20181015_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentHostMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(max_length=30)),
                ('component_version', models.CharField(default='0', max_length=30)),
                ('host_info', models.ManyToManyField(through='cmdb.ComponentHostMapping', to='cmdb.HostBasicInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='clusterbasicinfo',
            name='host_info',
            field=models.ManyToManyField(through='cmdb.ClusterHostMapping', to='cmdb.HostBasicInfo'),
        ),
        migrations.AddField(
            model_name='componenthostmapping',
            name='component_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.ComponentInfo'),
        ),
        migrations.AddField(
            model_name='componenthostmapping',
            name='host_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.HostBasicInfo'),
        ),
    ]
