# Generated by Django 2.1.1 on 2018-10-18 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0023_auto_20181017_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterbasicinfo',
            name='host_info',
            field=models.ManyToManyField(through='cmdb.ClusterHostMapping', to='cmdb.HostBasicInfo'),
        ),
        migrations.AlterField(
            model_name='componenthostmapping',
            name='host_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_component', to='cmdb.HostBasicInfo'),
        ),
    ]
